name: IndividualMessages
main: com.empcraft.individualmessages.IndividualMessages
version: 0.0.1
author: Empire92
website: www.empcraft.com
depend: [Vault,ProtocolLib]
commands:
   isp:
      description: InSignsPlus commands.